---

# 前提条件:
# - 配置网络
# - 安装ansible 
- hosts: localhost
  pre_tasks:
    - name: 更新pacman缓存
      pacman: update_cache=yes 
  tasks:
    - name:  配置用户
      user: name=lujun9972 groups=wheel shell=/bin/bash

    #- name: set password for lujun9972
    #  var_prompt:
    #    - name: user_pwd
    #      prompt: "set the password for lujun9972:"
    #      private: yes 
    #  command: passwd lujn9972

    - name: 配置sudo,让wheel组的用户能够suduo
      lineinfile:
        path: /etc/sudoers
        line: '%wheel ALL=(ALL) ALL'

    - name: 查看/etc/pacman.conf配置
      command: cat /etc/pacman.conf
      register: pacman_conf

    - name: 添加Archlinux CN 镜像源
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [archlinuxcn]
          SigLevel = Optional TrustedOnly
          Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch
    - name: 安装archlinuxcn-keyring
      pacman: name=archlinuxcn-keyring state=latest

    - name: 安装必要软件
      pacman: "name={{item}} state=latest"
      with_items:
        - yaourt
        - fcitx-im
        - fcitx-configtool
        - fcitx-sunpinyin
        - git
        - openssh
        - pandoc
        - emacs
        - shadowsocks
        - alsa-utils
        - wps-office
        - ttf-wps-fonts
        - smplayer
        - mpg123
        - cmake

    - name: 安装图形环境
      pacman: "name={{item}} state=latest"
      with_items:
        - xorg
        #- xorg-server
        - xorg-xinit
        - ttf-dejavu
        - wqy-microhei
        - awesome
        - archlinux-xdg-menu
        - shadowsocks-qt5
        - nutstore
        - zeal

    #- name: 安装fbterm支持中文显示
    #  sudo_user: lujun9972
    #  sudo: yes
    #  command: yaourt -S --noconfirm fbterm-git libx86
    #  args:
    #    creates: /usr/bin/fbterm
    #- name: 设置用户组
    #  user: name=lujun9972 groups=video append=yes
    #- name: 设置fbterm权限
    #  command: "setcap 'cap_sys_tty_config+ep' /usr/bin/fbterm"

      # 使用fcitx-fbterm作为中文输入法
    - name: clone fcitx-fbterm
      git: accept_hostkey=yes depth=1 dest=/tmp/fcitx-fbterm repo=https://github.com/fcitx/fcitx-fbterm
    - name: install fcitx-fbterm
      shell: cd /tmp/fcitx-fbterm && mkdir -p build && cd build && cmake .. && make && make install
      args:
        creates: /usr/local/bin/fcitx-fbterm-helper

    - name: 安装其他frambuffer工具
      pacman: "name={{item}} state=latest"
      with_items:
        - xorg-server-xvfb
        - xf86-video-fbdev
        - fbset
        - moc
        - netease-musicbox-git
        - cmus
        - w3m
        - imlib2
        - aria2
        # 关于newsbeuter的用法可以参见[[https://linuxtoy.org/archives/newsbeuter.html][Newsbeuter：在控制台下读 RSS 新闻]]
        - newsbeuter
        - fbida
        - fbgrab

    - name: 安装其他可选软件
      pacman: "name={{item}} state=latest"
      with_items:
        - terminator
        - rox
        - feh
        - sxiv
        - mpv

    - name: 配置git
      sudo_user: lujun9972
      sudo: yes
      git_config: "scope=global name={{item.option}} value={{item.value}}"
      with_items:
        - option: user.email
          value: "lujun9972@gmail.com"
        - option: user.name
          value: "darksun"
        - option: core.quotepath
          value: false
        - option: diff.tool
          value: ediff
        - option: difftool.ediff.cmd
          value: '~/bin/ediff.sh \"\$LOCAL\" \"\$REMOTE\"'
        - option: difftool.prompt
          value: false
        - option: merge.tool
          value: ediff
        - option: mergetool.ediff.cmd
          value:  '~/bin/ediff_merge.sh \"$BASE\" \"\$LOCAL\" \"\$REMOTE\" \"$MERGED\"'
        - option: mergetool.prompt
          value: false

    - name: 启动sshd
      systemd: name=sshd.service enabled=yes state=started

    - name: 生成私钥文件
      sudo_user: lujun9972
      sudo: yes
      block:
        - shell: ssh-keygen -t rsa -f ~/.ssh/id_rsa -P ''
          args:
            creates: ~/.ssh/id_rsa

        - shell: cat ~/.ssh/id_rsa.pub
          register: ssh_pub_key

    # - name: Authorize key with Github
    #   github_key: name=test token={{github_access_token}} pubkey={{ssh_pub_key.stdout}}



# * Emacs
# 2. 安装配置
#    #+BEGIN_SRC sh
#      git clone git@github.com:lujun9972/bin.git ~/bin
#      git clone git@github.com:lujun9972/MyLisp.git ~/MyLisp
#      git clone git@github.com:lujun9972/.spacemacs.d.git ~/.spacemacs.d
#      mv ~/.emacs.d ~/emacs.d
#      git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
#    #+END_SRC
# 3. spacemacs的python layer需要安装virtualenvwrapper
#    #+BEGIN_SRC shell :dir /sudo::
#      pacman --noconfirm -S python-virtualenvwrapper
#    #+END_SRC




# 5. 生成awesome menu
#    #+BEGIN_SRC sh 
#      xdg_menu --format awesome --root-menu /etc/xdg/menus/arch-applications.menu >~/.config/awesome/archmenu.lua
#    #+END_SRC
