---
- name: 安装AUR中的package
  become_user: "{{user_name}}"
  become: yes
  command: "yaourt -S --noconfirm {{item.name}}"
  args:
    creates: "{{item.object}}"
  with_items:
    - name: "anki20-bin"
      object: "/usr/bin/anki"
  tags: aur,package
