---
- name: install bash-it
  become_user: "{{user_name}}"
  become: yes
  block:
    - git: accept_hostkey=yes dest=~/.bash-it repo=https://github.com/Bash-it/bash-it.git depth=1
    - shell: "~/.bash-it/install.sh --silent"
  tags: configuration

- name: download configurations dotfile
  become_user: "{{user_name}}"
  become: yes
  get_url: dest=/tmp/dotfile.org url=https://raw.githubusercontent.com/lujun9972/dotfile/master/dotfile.org force=yes
  tags: configuration

- name: recover configurations
  become_user: "{{user_name}}"
  become: yes
  shell: "yes -- --|emacs --batch  /tmp/dotfile.org --eval '(org-babel-tangle)'"
  tags: configuration

