---
- name: 安装fbterm支持中文显示
  become_user: lujun9972
  become: yes
  command: yaourt -S --noconfirm fbterm-git libx86
  args:
    creates: /usr/bin/fbterm
- name: 设置用户组
  user: name=lujun9972 groups=video append=yes
- name: 设置fbterm权限
  command: "setcap 'cap_sys_tty_config+ep' /usr/bin/fbterm"

- name: 使用fcitx-fbterm作为中文输入法
  block:
    - git: accept_hostkey=yes depth=1 dest=/tmp/fcitx-fbterm repo=https://github.com/fcitx/fcitx-fbterm
    - shell: cd /tmp/fcitx-fbterm && mkdir -p build && cd build && cmake .. && make && make install
      args:
        creates: /usr/local/bin/fcitx-fbterm-helper

- name: 安装其他frambuffer工具
  pacman: "name={{item}} state=latest"
  with_items:
    - xorg-server-xvfb
    - xf86-video-fbdev
    - fbset
    - moc
    - netease-musicbox-git
    - cmus
    - w3m
    - imlib2
    - aria2
    # 关于newsbeuter的用法可以参见[[https://linuxtoy.org/archives/newsbeuter.html][Newsbeuter：在控制台下读 RSS 新闻]]
    - newsbeuter
    - fbida
    - fbgrab
