---
- name: 安装其他frambuffer工具
  pacman: "name={{item}} state=latest"
  with_items:
    - xorg-server-xvfb
    - xf86-video-fbdev
    - fbset
    - moc
    - cmus
    - w3m
    - imlib2
    - aria2
    # 关于newsbeuter的用法可以参见[[https://linuxtoy.org/archives/newsbeuter.html][Newsbeuter：在控制台下读 RSS 新闻]]
    #- newsbeuter
    - fbida
    # - fbcat
    - antiword
