---
- name: 配置sudo,让wheel组的用户能够suduo
  lineinfile:
    path: /etc/sudoers
    line: '%wheel ALL=(ALL) ALL'

- name: 配置sudoer,配置sudo日志
  lineinfile:
    path: /etc/sudoers
    line: 'Defaults     logfile=/var/log/sudo.log'
